name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7
        terraform_wrapper: false

    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y unzip
        make setup

    - name: Apply Terraform configuration
      id: apply-terraform
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

    - name: Get RDS endpoint
      id: get-rds-endpoint
      run: |
        cd terraform
        terraform output -raw rds_endpoint > rds_endpoint.txt
        cat rds_endpoint.txt  # Debugging step to check the output
        RDS_ENDPOINT=$(cat rds_endpoint.txt)
        echo "RDS_ENDPOINT=${RDS_ENDPOINT}" >> $GITHUB_ENV
        echo "RDS_ENDPOINT=${RDS_ENDPOINT}"  # This will print to the standard output
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

    - name: Create database schema
      run: |
        . venv/bin/activate
        python scripts/create_schema.py
      env:
        RDS_ENDPOINT: ${{ env.RDS_ENDPOINT }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        
    - name: Load data into RDS
      run: |
        . venv/bin/activate
        python scripts/load_data.py
      env:
        RDS_ENDPOINT: ${{ env.RDS_ENDPOINT }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

    - name: Run tests
      run: |
        . venv/bin/activate
        python -m unittest discover -s tests

